(function(){function a(){f||(f=!0,c[d].load[e]("firstScrollTime"))}var c=window,d="jstiming",e="tick",b=function(a){this.t={};this.tick=function(a,b,c){c=void 0!=c?c:(new Date).getTime();this.t[a]=[c,b]};this[e]("start",null,a)},l=new b;c.jstiming={Timer:b,load:l};if(c.performance&&c.performance.timing){var b=c.performance.timing,h=c[d].load,k=b.navigationStart,b=b.responseStart;0<k&&b>=k&&(h[e]("_wtsrt",void 0,k),h[e]("wtsrt_","_wtsrt",b),h[e]("tbsd_","wtsrt_"))}try{b=null,c.chrome&&c.chrome.csi&&
(b=Math.floor(c.chrome.csi().pageT),h&&0<k&&(h[e]("_tbnd",void 0,c.chrome.csi().startE),h[e]("tbnd_","_tbnd",k))),null==b&&c.gtbExternal&&(b=c.gtbExternal.pageT()),null==b&&c.external&&(b=c.external.pageT,h&&0<k&&(h[e]("_tbnd",void 0,c.external.startE),h[e]("tbnd_","_tbnd",k))),b&&(c[d].pt=b)}catch(g){}c.tickAboveFold=function(a){var b=0;if(a.offsetParent){do b+=a.offsetTop;while(a=a.offsetParent)}750>=b&&c[d].load[e]("aft")};var f=!1;c.addEventListener?c.addEventListener("scroll",a,!1):c.attachEvent("onscroll",
a)})();

(function(a,c,d){a.fn.tinyNav=function(e){var b=a.extend({active:"selected",header:"",label:""},e);return this.each(function(){d++;var e=a(this),h="tinynav"+d,k=".l_"+h,g=a("<select/>").attr("id",h).addClass("tinynav "+h);if(e.is("ul,ol")){""!==b.header&&g.append(a("<option/>").text(b.header));var f="";e.addClass("l_"+h).find("a").each(function(){f+='<option value="'+a(this).attr("href")+'">';var b;for(b=0;b<a(this).parents("ul, ol").length-1;b++)f+="- ";f+=a(this).text()+"</option>"});g.append(f);b.header||
g.find(":eq("+a(k+" li").index(a(k+" li."+b.active))+")").attr("selected",!0);g.change(function(){c.location.href=a(this).val()});a(k).after(g);b.label&&g.before(a("<label/>").attr("for",h).addClass("tinynav_label "+h+"_label").append(b.label))}})}})(jQuery,this,0);

(function(a,c){function d(){var a=s.elements;return"string"==typeof a?a.split(" "):a}function e(a){var b=r[a[q]];b||(b={},m++,a[q]=m,r[m]=b);return b}function b(a,b,d){b||(b=c);if(n)return b.createElement(a);d||(d=e(b));b=d.cache[a]?d.cache[a].cloneNode():f.test(a)?(d.cache[a]=d.createElem(a)).cloneNode():d.createElem(a);return b.canHaveChildren&&!g.test(a)?d.frag.appendChild(b):b}function l(a,c){c.cache||(c.cache={},c.createElem=a.createElement,c.createFrag=a.createDocumentFragment,c.frag=c.createFrag());
a.createElement=function(e){return s.shivMethods?b(e,a,c):c.createElem(e)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+d().join().replace(/\w+/g,function(a){c.createElem(a);c.frag.createElement(a);return'c("'+a+'")'})+");return n}")(s,c.frag)}function h(a){a||(a=c);var b=e(a);if(s.shivCSS&&!p&&!b.hasCSS){var d,f=a;d=f.createElement("p");f=f.getElementsByTagName("head")[0]||f.documentElement;d.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}</style>";
d=f.insertBefore(d.lastChild,f.firstChild);b.hasCSS=!!d}n||l(a,b);return a}var k=a.html5||{},g=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,f=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,p,q="_html5shiv",m=0,r={},n;(function(){try{var a=c.createElement("a");a.innerHTML="<xyz></xyz>";p="hidden"in a;var b;if(!(b=1==a.childNodes.length)){c.createElement("a");var d=c.createDocumentFragment();b="undefined"==typeof d.cloneNode||
"undefined"==typeof d.createDocumentFragment||"undefined"==typeof d.createElement}n=b}catch(e){n=p=!0}})();var s={elements:k.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup main mark meter nav output progress section summary time video",version:"3.6.2pre",shivCSS:!1!==k.shivCSS,supportsUnknownElements:n,shivMethods:!1!==k.shivMethods,type:"default",shivDocument:h,createElement:b,createDocumentFragment:function(a,b){a||(a=c);if(n)return a.createDocumentFragment();
b=b||e(a);for(var f=b.frag.cloneNode(),g=0,h=d(),k=h.length;g<k;g++)f.createElement(h[g]);return f}};a.html5=s;h(c)})(this,document);(function(a){var c=a("#search"),d=c.find(":text");c.append('<div id="search-result"></div>');var e=a("#search-result");c.on("submit",function(){var b=d.val();e.show().html("Loading...");a.ajax({url:"/feeds/posts/summary?alt=json-in-script&q="+b+"&max-results=9999",type:"get",dataType:"jsonp",success:function(a){a=a.feed.entry;var c,d="";if(void 0!==a){for(var d="<h4>Search results for keyword &quot;"+b+"&quot;</h4>",d=d+'<a class="close" href="/">&times;</a><ol>',g=0;g<a.length;g++){for(var f=0;f<
a[g].link.length;f++)"alternate"==a[g].link[f].rel&&(c=a[g].link[f].href);d+='<li><a href="'+c+'">'+a[g].title.$t+"</a></li>"}e.html(d+"</ol>")}else e.html('<a class="close" href="/">&times;</a><strong>No result!</strong>')},error:function(){e.html('<a class="close" href="/">&times;</a><strong>Error loading feed.</strong>')}});return!1});c.on("click",".close",function(){e.fadeOut();return!1})})(jQuery);
